// 主线第二部「七大圣」：40~150 级。纯数据，由 game.js 拼接到主线末尾
// goal / reward 格式与 game.js 的 MAIN 相同；reward.jade 为仙玉
export const STORY2 = [
  { title: '猴王何在', giver: 'hg_monkey', lv: 40,
    accept: ['少侠来得正好！五百年前大圣被压在五行山下，花果山群龙无首。', '如今山里的<b>巨力神猿</b>受了妖气蛊惑，见人就打。先帮我打退<b>8只巨力神猿</b>吧！'],
    goal: { type: 'kill', mid: 'julishenyuan', n: 8, map: 'huaguo' }, turnin: 'hg_monkey',
    done: ['多谢少侠！可神猿们说，是一个自称<b>混世魔王</b>的家伙占了水帘洞，到处散播妖气。'],
    reward: { expF: 0.8, gold: 8000, jade: 50 } },
  { title: '水帘洞', giver: 'hg_monkey', lv: 44,
    accept: ['混世魔王就在水帘洞前（花果山 46,22）。此妖力大无穷，惯用<b>横扫千军</b>。', '首领气血低于四成时会<b>狂暴</b>，伤害大增！<br><i>建议等级46以上，带满伙伴，多备药品。</i>'],
    goal: { type: 'boss', boss: 'hunshi', map: 'huaguo', x: 46, y: 22 }, turnin: 'hg_monkey',
    done: ['（混世魔王化作一缕黑烟）「七大圣……很快就会重聚……三界……」', '七大圣？那是五百年前与大圣结拜的七位妖王！难道有人要重组妖盟？', '东海龙王前些日子派人来打听消息，说龙宫丢了宝物。少侠不妨去<b>东海龙宫</b>找<b>龟丞相</b>问问。<br><i>东海龙宫的入口在东海湾海边（38,12）。</i>'],
    reward: { expF: 1.2, gold: 15000, jade: 100, equip: { slot: 'weapon', tier: 5, rarity: 2 }, title: '花果山恩人' } },
  { title: '龙宫告急', giver: 'hg_monkey', lv: 50,
    accept: ['东海龙宫就在东海湾海边的传送阵下面，去找<b>龟丞相</b>吧。'],
    goal: { type: 'talk', npc: 'lg_guicheng' },
    done: ['少侠来得正好！前日<b>九头虫</b>潜入龙宫，盗走了镇宫之宝<b>九叶灵芝草</b>，还纠集了一群巡海夜叉作乱！'],
    reward: { expF: 0.5, gold: 5000 } },
  { title: '巡海夜叉', giver: 'lg_guicheng', auto: true, lv: 52,
    accept: ['先清理龙宫里作乱的<b>10只巡海夜叉</b>，九头虫失了爪牙，才好对付。'],
    goal: { type: 'kill', mid: 'yecha', n: 10, map: 'longgong' }, turnin: 'lg_guicheng',
    done: ['干得漂亮！夜叉们一退，九头虫就躲回水晶宫里去了。'],
    reward: { expF: 1, gold: 12000, jade: 50, items: [['dahuan', 10]] } },
  { title: '九头虫', giver: 'lg_guicheng', lv: 56,
    accept: ['九头虫就在<b>水晶宫</b>前（东海龙宫 32,15）。它会呼风唤雨，法术极强。<br><i>建议等级58以上。抗法修炼和治疗伙伴会很有帮助。</i>'],
    goal: { type: 'boss', boss: 'jiutouchong', map: 'longgong', x: 32, y: 15 }, turnin: 'lg_guicheng',
    done: ['九叶灵芝草终于回来了！', '（九头虫临死前吐出一枚<b>妖盟令牌</b>，上面刻着「覆海」二字）', '覆海大圣<b>蛟魔王</b>……他在<b>北俱芦洲</b>闭关。龙王的小女儿<b>龙女</b>自愿随你北上！<br><i>北俱芦洲的入口在花果山西南角（6,44）。</i>'],
    reward: { expF: 1.5, gold: 20000, jade: 150, partner: 'longnv' } },
  { title: '覆海之谋', giver: 'lg_guicheng', lv: 62,
    accept: ['北俱芦洲的<b>雪山老人</b>熟悉那里的一草一木，去找他打听蛟魔王的下落。'],
    goal: { type: 'talk', npc: 'bj_elder' },
    done: ['蛟魔王？唉……自从他来了，山上的<b>雪狼</b>每晚都下山伤人。'],
    reward: { expF: 0.5, gold: 8000 } },
  { title: '冰原狼群', giver: 'bj_elder', auto: true, lv: 64,
    accept: ['帮老朽赶走<b>10只雪狼</b>，老朽就告诉你蛟魔王的洞府在哪。'],
    goal: { type: 'kill', mid: 'xuelang', n: 10, map: 'beiju' }, turnin: 'bj_elder',
    done: ['好身手！蛟魔王就在北边的冰崖下修炼，千万小心。'],
    reward: { expF: 1, gold: 15000, jade: 50, items: [['qianghua', 5]] } },
  { title: '覆海大圣', giver: 'bj_elder', lv: 67,
    accept: ['蛟魔王在冰崖下（北俱芦洲 28,14）。他枪法凌厉，又会二龙戏珠。<br><i>建议等级69。</i>'],
    goal: { type: 'boss', boss: 'jiaomowang', map: 'beiju', x: 28, y: 14 }, turnin: 'bj_elder',
    done: ['蛟魔王：「哈哈哈……你以为赢了？<b>平天大圣</b>早已在火焰山布下天罗地网！」', '平天大圣便是牛魔王！看来妖盟要在火焰山聚首。', '<i>凡人修行到69级便会遇到瓶颈。去长安城找<b>太白金星</b>渡劫突破，才能继续升级。</i>'],
    reward: { expF: 1.5, gold: 30000, jade: 200, equip: { slot: 'armor', tier: 6, rarity: 3 } } },
  { title: '西行火焰山', giver: 'bj_elder', lv: 70,
    accept: ['火焰山在大唐境外的西南角（6,46）。去找<b>火焰山土地</b>，他知道牛魔王的底细。'],
    goal: { type: 'talk', npc: 'hy_tudi' },
    done: ['少侠要过火焰山？此山八百里火焰，须<b>芭蕉扇</b>才能扇灭。', '可恨牛魔王的儿子<b>红孩儿</b>占了火云洞，四处放火……'],
    reward: { expF: 0.5, gold: 10000 } },
  { title: '圣婴大王', giver: 'hy_tudi', auto: true, lv: 74,
    accept: ['红孩儿就在<b>火云洞</b>前（火焰山 26,35），他的三昧真火厉害得很！'],
    goal: { type: 'boss', boss: 'honghaier', map: 'huoyan', x: 26, y: 35 }, turnin: 'hy_tudi',
    done: ['观音菩萨现身收服了红孩儿，从此皈依佛门，法号<b>善财童子</b>。', '菩萨让善财童子随你一同历练，以赎前罪。'],
    reward: { expF: 1.2, gold: 25000, jade: 100, partner: 'shancai' } },
  { title: '借扇', giver: 'hy_tudi', lv: 78,
    accept: ['芭蕉扇在红孩儿的母亲<b>铁扇公主</b>手里，她就在<b>芭蕉洞</b>（火焰山 44,15）。', '儿子被收，她正恨你入骨，怕是只能硬借了。'],
    goal: { type: 'boss', boss: 'tieshan', map: 'huoyan', x: 44, y: 15 }, turnin: 'hy_tudi',
    done: ['铁扇公主交出了扇子……可一扇下去，火势反而更旺了！这是<b>假扇</b>！', '真扇在牛魔王身上。他就在<b>积雷山</b>。'],
    reward: { expF: 1.2, gold: 30000, jade: 100, items: [['jinke2', 1]] } },
  { title: '平天大圣', giver: 'hy_tudi', lv: 84,
    accept: ['牛魔王在<b>积雷山</b>（火焰山 56,40）。他似乎被什么东西控制了，双眼血红，力大无穷。<br><i>建议等级88以上。</i>'],
    goal: { type: 'boss', boss: 'niumowang', map: 'huoyan', x: 56, y: 40 }, turnin: 'hy_tudi',
    done: ['牛魔王清醒过来：「俺老牛这是怎么了……有个和大圣<b>一模一样的猴子</b>，往俺体内种了魔种！」', '一模一样的猴子？他说那猴子最后往<b>无底洞</b>方向去了。', '<i>89级是第二道瓶颈，别忘了去太白金星处突破。</i>'],
    reward: { expF: 1.8, gold: 50000, jade: 300, equip: { slot: 'weapon', tier: 8, rarity: 3 }, title: '火焰山英雄' } },
  { title: '陷空山', giver: 'hy_tudi', lv: 90,
    accept: ['无底洞在火焰山西南（3,44），洞口有个<b>落难僧人</b>，或许知道些什么。'],
    goal: { type: 'talk', npc: 'wd_monk' },
    done: ['施主救命！洞里的<b>地涌夫人</b>把僧众都抓了去，还有成群的鼠精看守……'],
    reward: { expF: 0.5, gold: 15000 } },
  { title: '鼠辈横行', giver: 'wd_monk', auto: true, lv: 92,
    accept: ['请施主先除掉<b>12只鼠精</b>，贫僧好把被困的师兄弟救出来。'],
    goal: { type: 'kill', mid: 'shujing', n: 12, map: 'wudi' }, turnin: 'wd_monk',
    done: ['阿弥陀佛，师兄弟们都逃出来了！地涌夫人就在洞底最深处。'],
    reward: { expF: 1.2, gold: 30000, jade: 80, items: [['qianghua', 8]] } },
  { title: '地涌夫人', giver: 'wd_monk', lv: 96,
    accept: ['地涌夫人在洞底（无底洞 40,12），她本是金鼻白毛老鼠精，身法极快，还会魅惑之术。<br><i>建议等级99以上。</i>'],
    goal: { type: 'boss', boss: 'diyong', map: 'wudi', x: 40, y: 12 }, turnin: 'wd_monk',
    done: ['（托塔天王李靖与哪吒三太子驾云而至，收走了地涌夫人）', '哪吒：「这妖精是我父王的义女，给你添麻烦了。天庭近来也不太平，本太子便随你走一遭！」', '哪吒说<b>南天门</b>正被妖兵围攻，要你速去支援。<br><i>南天门在北俱芦洲东北角（60,5）。</i>'],
    reward: { expF: 1.5, gold: 50000, jade: 200, partner: 'nezha' } },
  { title: '南天门告急', giver: 'wd_monk', lv: 100,
    accept: ['南天门在北俱芦洲东北角，去找守将<b>增长天王</b>。'],
    goal: { type: 'talk', npc: 'nt_general' },
    done: ['援军到了！妖兵从四面八方攻来，混天大圣<b>鹏魔王</b>亲自督战！'],
    reward: { expF: 0.5, gold: 20000 } },
  { title: '天兵退妖', giver: 'nt_general', auto: true, lv: 103,
    accept: ['先击退<b>12个妖兵</b>，稳住阵脚！'],
    goal: { type: 'kill', mid: 'yaobing', n: 12, map: 'nantian' }, turnin: 'nt_general',
    done: ['妖兵退了！鹏魔王恼羞成怒，亲自杀到了南天门下。'],
    reward: { expF: 1.2, gold: 40000, jade: 100 } },
  { title: '混天大圣', giver: 'nt_general', lv: 108,
    accept: ['鹏魔王就在南天门下（32,15），他快如疾风，鹰击群攻无人能挡。<br><i>建议等级110以上。</i>'],
    goal: { type: 'boss', boss: 'pengmowang', map: 'nantian', x: 32, y: 15 }, turnin: 'nt_general',
    done: ['鹏魔王败退，却狂笑道：「<b>移山大圣</b>就在斗牛宫后，你们守不住的！」', '<i>109级是第三道瓶颈。</i>'],
    reward: { expF: 1.5, gold: 60000, jade: 200 } },
  { title: '移山大圣', giver: 'nt_general', lv: 114,
    accept: ['狮驼王在斗牛宫后（南天门 54,39），皮糙肉厚，擅长后发制人。'],
    goal: { type: 'boss', boss: 'shituowang', map: 'nantian', x: 54, y: 39 }, turnin: 'nt_general',
    done: ['狮驼王：「是六耳……不，是大圣……他拿着<b>生死簿</b>……」话没说完便昏死过去。', '生死簿在<b>幽冥地府</b>。增长天王请你速去找<b>崔判官</b>。<br><i>幽冥地府的入口在大唐国境南边（30,52）。</i>'],
    reward: { expF: 1.8, gold: 80000, jade: 300, equip: { slot: 'armor', tier: 11, rarity: 3 }, title: '天庭护法' } },
  { title: '生死簿', giver: 'nt_general', lv: 118,
    accept: ['去幽冥地府森罗殿前找<b>崔判官</b>。'],
    goal: { type: 'talk', npc: 'ym_panguan' },
    done: ['少侠！生死簿被人撕去一页，猴属之名全被勾销……', '阴兵也趁乱暴动了！'],
    reward: { expF: 0.5, gold: 30000 } },
  { title: '阴兵作乱', giver: 'ym_panguan', auto: true, lv: 120,
    accept: ['请少侠平定<b>12个阴兵</b>，地府才好追查真凶。'],
    goal: { type: 'kill', mid: 'yinbing', n: 12, map: 'youming' }, turnin: 'ym_panguan',
    done: ['阴兵平定了。据鬼差回报，撕毁生死簿的是<b>驱神大圣禺狨王</b>！'],
    reward: { expF: 1.2, gold: 50000, jade: 100, items: [['xiulian', 5]] } },
  { title: '驱神大圣', giver: 'ym_panguan', lv: 125,
    accept: ['禺狨王藏在忘川河南岸（幽冥地府 10,41）。<br><i>建议等级128以上。</i>'],
    goal: { type: 'boss', boss: 'yurongwang', map: 'youming', x: 10, y: 41 }, turnin: 'ym_panguan',
    done: ['禺狨王：「我等只是棋子……真正的主人，是那<b>六耳猕猴</b>！」', '六耳猕猴？唯有<b>谛听</b>能辨真假，它在地府西北的翠云宫前。'],
    reward: { expF: 1.5, gold: 80000, jade: 200 } },
  { title: '谛听', giver: 'ym_panguan', lv: 128,
    accept: ['去翠云宫前拜见神兽<b>谛听</b>。'],
    goal: { type: 'talk', npc: 'ym_diting' },
    done: ['（谛听伏地良久，缓缓开口）「那妖猴善聆音，能察理，知前后，万物皆明。它假扮齐天大圣，欲夺三界。」', '「它藏身于西天路上的<b>小雷音寺</b>，与黄眉怪勾结。去吧，三界的命运在你手中。」', '<i>129级是最后一道瓶颈。小雷音寺在无底洞西北角（4,4）。</i>'],
    reward: { expF: 0.8, gold: 40000, jade: 100 } },
  { title: '黄眉大王', giver: 'ym_diting', lv: 134,
    accept: ['黄眉大王盘踞小雷音寺（32,16），手中<b>人种袋</b>能收尽天兵。事成后去见寺外的<b>弥勒佛</b>。<br><i>建议等级138以上。</i>'],
    goal: { type: 'boss', boss: 'huangmei', map: 'leiyin', x: 32, y: 16 }, turnin: 'ly_mile',
    done: ['弥勒佛：「呵呵，孽畜，还不现形！」黄眉童子被收了回去。', '「那六耳猕猴就在寺旁的<b>假灵山</b>。它的本事与大圣一般无二，少侠务必小心。」'],
    reward: { expF: 1.8, gold: 100000, jade: 300, equip: { slot: 'weapon', tier: 13, rarity: 3 } } },
  { title: '真假美猴王', giver: 'ly_mile', lv: 142,
    accept: ['最后的决战！六耳猕猴就在假灵山（小雷音寺 14,25）。<br><i>建议等级145以上。装备强化、修炼、伙伴升星都能助你一臂之力。</i>'],
    goal: { type: 'boss', boss: 'liuer', map: 'leiyin', x: 14, y: 25 }, turnin: 'ly_mile',
    done: ['六耳猕猴被打回原形，七大圣之乱终告平息。', '弥勒佛：「少侠功德无量，三界从此太平。这只<b>超级神龙</b>便赠予你吧。」', '<i>七大圣篇完结！可以继续挑战镇妖塔、华山论剑，冲击150级！</i>'],
    reward: { expF: 3, gold: 300000, jade: 1000, pet: 'ss_long', title: '三界守护者' } },
];

// 首领战阵容：[怪物, 等级]
export const BOSS_FIGHTS2 = {
  hunshi: [['hunshi', 50], ['julishenyuan', 47], ['julishenyuan', 47], ['changmei', 47], ['changmei', 47]],
  jiutouchong: [['jiutouchong', 60], ['yecha', 58], ['yecha', 58], ['jiaoren', 58], ['jiaoren', 58]],
  jiaomowang: [['jiaomowang', 70], ['xuelang', 67], ['xuelang', 67], ['bingyao', 67], ['fengbo', 67]],
  honghaier: [['honghaier', 78], ['huojing', 76], ['huojing', 76], ['yanhu', 76], ['yanhu', 76]],
  tieshan: [['tieshan', 82], ['yanhu', 80], ['yanhu', 80], ['huojing', 80], ['niujiang', 80]],
  niumowang: [['niumowang', 89], ['niujiang', 86], ['niujiang', 86], ['huojing', 86], ['huojing', 86]],
  diyong: [['diyong', 100], ['shujing', 97], ['shujing', 97], ['zhizhunv', 97], ['xiezi', 97]],
  pengmowang: [['pengmowang', 112], ['yaobing', 109], ['tianbing', 109], ['leigong', 109]],
  shituowang: [['shituowang', 118], ['tianbing', 115], ['leigong', 115], ['yaobing', 115]],
  yurongwang: [['yurongwang', 129], ['yinbing', 126], ['yinbing', 126], ['gouhun', 126], ['wuchang', 126]],
  huangmei: [['huangmei', 138], ['yaoseng', 135], ['yaoseng', 135], ['jingang', 135], ['mohou', 135]],
  liuer: [['liuer', 148], ['mohou', 145], ['mohou', 145], ['jingang', 145], ['yaoseng', 145]],
};
